version: '3'

services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - incepnet
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
    
  mariadb:
    image: mariadb
    env_file:
      - .env
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - incepnet
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    image: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
        WPADUSER: ${WPADUSER}
        WPUSER1: ${WPUSER1}
        WPADPASS: ${WPADPASS}
        WPUSER1PASS: ${WPUSER1PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - incepnet
    restart: always
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    incepnet:
        driver: bridge
