version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    # image: nginx:stable-alpine
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    # restart: alway (is it needed??)
    ports:
      - "443:443"
    networks:
      - incep_net
    depends_on:
      - wordpress
    container_name: nginx
    # image_name: nginx
    # depends_on:
    #   - wordpress
    
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - incep_net
    restart: always
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    incep_net:
        driver: bridge

# version:

# services:
    #container:
#       image:
#       build:
#       volumes:
#       environment:
#       container_name:
#       image_name: 
#       networks:
#       ports:
#       command:
#       depends_on:

# volumes:

# networks:
#       #for wordpress
#       #for mariadb