# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: arafeeq <arafeeq@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/02 05:03:42 by arafeeq           #+#    #+#              #
#    Updated: 2023/06/02 08:54:28 by arafeeq          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#the image used for the conatainer
FROM alpine:3.13

# set our wrkdir. The following instructions will be executed in this location.
WRKDIR <location>

# Copy the <file> file from <location> to WRKDIR location
COPY <file> <location>

# dependencies needed
RUN

# to create an environment variable.
# We can access ENV values during the build, as well as once the container runs.
ENV

# command that is executed on 'docker container run'
# i.e the command to run the application
CMD

#to confugure executables that will always run after the container is initiated/launched
ENTRYPOINT

# Exposing a container port
# telling Docker that the container listens to a certain port
EXPOSE <port>
